[world]
name = "Grid Guru"
description = "8 x 8 Grid Battle Simulation."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "shinigami_templa"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "grid_guru"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
# Default account for katana with seed = 0
account_address = "0x02A54eFf65D55a2E7D2fC7E23eF0F0e6030dB0313b16c8F0eaD0b4a83807f6d6"
private_key = "0x0396533b7a1182ef03da483eca82e9dd2b17bee9c7fec07ac6cbbeb8bfd573cb"
world_address = "0x068a9625dd8df8cc003ceefa9758dc80c7886a29f7dabaf601164d604e55d9e0"

[writers]
"grid_guru" = ["grid_guru-actions"]
"grid_guru-TrophyCreation" = ["grid_guru-actions"]
"grid_guru-TrophyProgression" = ["grid_guru-actions"]
