[world]
name = "Grid Guru"
description = "8 x 8 Grid Battle Simulation."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "shinigami_template"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "grid_guru"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = ""
private_key = ""
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"grid_guru" = ["grid_guru-actions"]
"grid_guru-TrophyCreation" = ["grid_guru-actions"]
"grid_guru-TrophyProgression" = ["grid_guru-actions"]
