[world]
name = "Grid Guru"
description = "8 x 8 Grid Battle Simulation."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "shinigami_template"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "grid_guru"

[env]
rpc_url = "https://api.cartridge.gg/x/denver-grid/katana/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x000fb6b38cdca072996cdcf55d7f785f78bd930df1e8a5dfd4867987f254b8e7"

[writers]
"grid_guru" = ["grid_guru-actions"]
# "grid_guru-TrophyCreation" = ["grid_guru-actions"]
# "grid_guru-TrophyProgression" = ["grid_guru-actions"]
