rpc = "https://api.cartridge.gg/x/starknet/sepolia"

allowed_origins = ["*"]
# The World address to index.
world_address = "0x068a9625dd8df8cc003ceefa9758dc80c7886a29f7dabaf601164d604e55d9e0"

# Indexing Options
[indexing]
allowed_origins = ["*"]
pending = true
transactions = true
polling_interval = 1000
contracts = []

[events]
raw = true
historical = [
    "grid_guru-TrophyProgression",
]
