name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    env:
      DOJO_VERSION: v1.1.2
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.2"
      - name: Download Dojo release artifact
        run: |
          curl -L https://install.dojoengine.org | bash
          /home/runner/.config/.dojo/bin/dojoup -v ${{ env.DOJO_VERSION }}
      - name: Run Dojo Build
        run: |
          cd contracts && sozo build
      - name: Run Dojo Test
        run: |
          cd contracts && sozo test
